version: "3.8"

services:
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    ports:
      - 9200:9200
      - 9300:9300
  kb01:
    container_name: kb01
    image: docker.elastic.co/kibana/kibana:8.8.2
    ports:
      - 5601:5601
    depends_on:
      - es01